name: Deploy DocC to Pages

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docc:
    runs-on: self-hosted
    steps:
      - uses: adamcarlson/docc-action@main
        with:
          scheme: flowCoordinatorInvestigation
          base_pages_url: https://adamcarlson.github.io/flowCoordinatorInvestigation/
